{% set name = "libclc" %}
{% set version = "18.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/libclc-{{ version }}.src.tar.xz
    sha256: 905bd59e9f810d6bd0ae6874725a8f8a3c91cb416199c03f2b98b57437cfb32e

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
    - llvmdev  {{ version }}.*
    - llvm-spirv {{ ".".join(version.split(".")[:2]) }}.*
    - clang    {{ version }}.*
    - spirv-tools
    - zlib
  run_constrained:
    - llvmdev  {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/include/clc/clc.h          # [unix]
    - test -f ${PREFIX}/share/pkgconfig/libclc.pc  # [unix]
    - test -f ${PREFIX}/share/clc/nvptx64--.bc     # [unix]
    - test -f ${PREFIX}/share/clc/spirv64-mesa3d-.spv  # [unix]

about:
  home: https://llvm.org
  license: Apache-2.0
  license_file: LICENSE.TXT
  summary: |
    libclc is an open source, BSD licensed implementation of the library
    requirements of the OpenCL C programming language, as specified by the
    OpenCL 1.1 Specification.

extra:
  recipe-maintainers:
    - JarrettSJohnson
    - isuruf
