{% set version = "22.1.1" %}

package:
  name: libclc
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
    sha256: c48878550911a8a8993a749e6118446082656768e62b26456ac7d39c4422b409

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
    - llvmdev  {{ version }}.*                             # [build_platform != target_platform]
    - llvm-spirv {{ ".".join(version.split(".")[:2]) }}.*  # [build_platform != target_platform]
    - spirv-tools                                          # [build_platform != target_platform]
    - zlib                                                 # [build_platform != target_platform]
  host:
    - llvmdev  {{ version }}.*
    - llvm-spirv {{ ".".join(version.split(".")[:2]) }}.*
    - clang    {{ version }}.*
    - libxml2-devel
    - spirv-tools
    - zlib
    - zstd
  run_constrained:
    - llvmdev  {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/share/pkgconfig/libclc.pc  # [unix]
    - test -f ${PREFIX}/share/clc/nvptx64--.bc     # [unix]
    - test -f ${PREFIX}/share/clc/spirv64-mesa3d-.spv  # [unix]

about:
  home: https://llvm.org
  license: Apache-2.0
  license_file: LICENSE.TXT
  summary: |
    libclc is an open source, BSD licensed implementation of the library
    requirements of the OpenCL C programming language, as specified by the
    OpenCL 1.1 Specification.

extra:
  recipe-maintainers:
    - JarrettSJohnson
    - isuruf
