{% set name = "libclc" %}
{% set version = "16.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/libclc-{{ version }}.src.tar.xz
    sha256: b8f11158cd298062602285391496bb2acaf7219923fdd13b93927753c491e7c1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
    - llvmdev  {{ version }}.*
    - llvm-spirv {{ ".".join(version.split(".")[:2]) }}.*
    - clang    {{ version }}.*
    - spirv-tools
  run_constrained:
    - llvmdev  {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/include/clc/clc.h          # [unix]
    - test -f ${PREFIX}/share/pkgconfig/libclc.pc  # [unix]
    - test -f ${PREFIX}/share/clc/nvptx64--.bc     # [unix]

about:
  home: https://llvm.org
  license: Apache-2.0
  license_file: LICENSE.TXT
  summary: |
    libclc is an open source, BSD licensed implementation of the library
    requirements of the OpenCL C programming language, as specified by the
    OpenCL 1.1 Specification.

extra:
  recipe-maintainers:
    - isuruf
